# Generated by Django 5.2.7 on 2025-10-21 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_record'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='done',
        ),
        migrations.AlterField(
            model_name='record',
            name='completed_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='habit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='habits.habit'),
        ),
    ]
